# File: visualize_sparsity.py
import json
import os
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import matplotlib.colors as mcolors

# --- 1. Configuration ---
# The top-k sparse population file generated by evaluate_population_sparsity.py
SPARSE_POPULATION_FILE = "populations/evaluated_sparsity/plausible_population_topk_by_sparsity.json"

# The original, full population file (needed to get the baseline grid for comparison)
ORIGINAL_POPULATION_FILE = "populations/population_crit0_pop100000.json"

# Directory where the output images will be saved
OUTPUT_DIR = "visualizations_sparsity"

# The size of the highlight box to draw around the agent's critical position
HIGHLIGHT_BOX_SIZE = 0

# --- 2. Style Configuration (Identical to previous visualizers) ---
OBJECT_TO_INT = {"empty": 0, "Wall": 1, "Door": 2, "Key": 3, "Goal": 4}

custom_colors = [
    'white',       # 0: empty
    'darkgrey',    # 1: Wall
    'saddlebrown', # 2: Door
    'gold',        # 3: Key
    'limegreen'    # 4: Goal
]
cmap = mcolors.ListedColormap(custom_colors)
bounds = [i - 0.5 for i in range(len(OBJECT_TO_INT) + 1)]
norm = mcolors.BoundaryNorm(bounds, cmap.N)


# --- 3. Main Visualization Function (Modified to show sparsity score) ---
def plot_and_save_comparison(original_individual, modified_individual, output_path):
    """
    Generates and saves a side-by-side plot of the original grid vs. a sparse one.
    """
    # --- Extract Data ---
    original_grid_str = original_individual["grid"]
    modified_grid_str = modified_individual["grid"]

    agent_pos = tuple(original_individual["agent_pos"])
    episode_id = original_individual["meta"]["source_episode"]
    sparsity_score = modified_individual.get("sparsity_score", "N/A")

    # --- Convert string grids to integer arrays ---
    def grid_to_int_array(grid_str):
        return np.array([[OBJECT_TO_INT.get(tile, 0) for tile in row] for row in grid_str])

    original_grid_int = grid_to_int_array(original_grid_str)
    modified_grid_int = grid_to_int_array(modified_grid_str)

    # --- Create Subplots ---
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 8), dpi=100)
    fig.suptitle(f"Sparse Counterfactual Comparison (Source Episode: {episode_id})", fontsize=18, weight='bold')

    # --- Plot Original Grid (Left) ---
    ax1.imshow(original_grid_int, cmap=cmap, norm=norm, origin='lower')
    ax1.set_title("Original Environment", fontsize=14)

    # --- Plot Modified Grid (Right) ---
    ax2.imshow(modified_grid_int, cmap=cmap, norm=norm, origin='lower')
    title_text = f"Sparse Environment (Score: {sparsity_score:.3f})"
    ax2.set_title(title_text, fontsize=14)

    # --- Add Highlight Rectangle and Agent Marker to BOTH plots ---
    for ax in [ax1, ax2]:
        if HIGHLIGHT_BOX_SIZE > 0:
            radius = HIGHLIGHT_BOX_SIZE // 2
            rect_origin = (agent_pos[0] - radius - 0.5, agent_pos[1] - radius - 0.5)
            rect = patches.Rectangle(
                rect_origin, HIGHLIGHT_BOX_SIZE, HIGHLIGHT_BOX_SIZE,
                linewidth=2.5, edgecolor='cyan', facecolor='none', label='Area of Interest'
            )
            ax.add_patch(rect)

        ax.plot(agent_pos[0], agent_pos[1], 'r*', markersize=18, markeredgecolor='black', label="Agent's Position")
        ax.legend(loc='upper right')
        ax.set_xticks([])
        ax.set_yticks([])

    # --- Add a shared, descriptive colorbar ---
    cbar_ax = fig.add_axes([0.92, 0.25, 0.02, 0.5])
    mappable = plt.cm.ScalarMappable(cmap=cmap, norm=norm)
    cbar = fig.colorbar(mappable, cax=cbar_ax, ticks=np.arange(len(OBJECT_TO_INT)))
    cbar.ax.set_yticklabels(list(OBJECT_TO_INT.keys()), fontsize=12)

    plt.tight_layout(rect=[0, 0, 0.9, 1])
    plt.savefig(output_path, bbox_inches='tight')
    plt.close(fig)


# --- 4. Main Execution Block ---
if __name__ == "__main__":
    # --- File Validation ---
    if not os.path.exists(SPARSE_POPULATION_FILE):
        print(f"❌ Error: Sparse population file not found at '{SPARSE_POPULATION_FILE}'")
        print("Please run evaluate_population_sparsity.py first.")
    elif not os.path.exists(ORIGINAL_POPULATION_FILE):
        print(f"❌ Error: Original population file not found at '{ORIGINAL_POPULATION_FILE}'")
        print("This file is required to get the baseline environment for comparison.")
    else:
        # --- Load Data ---
        print(f"Loading sparse individuals from: {SPARSE_POPULATION_FILE}")
        with open(SPARSE_POPULATION_FILE, 'r') as f:
            sparse_data = json.load(f)

        print(f"Loading original individual from: {ORIGINAL_POPULATION_FILE}")
        with open(ORIGINAL_POPULATION_FILE, 'r') as f:
            original_pop_data = json.load(f)
        
        original_individual = original_pop_data[0]

        # --- Process and Visualize ---
        if sparse_data:
            os.makedirs(OUTPUT_DIR, exist_ok=True)
            print(f"\nVisualizations will be saved to the '{OUTPUT_DIR}' directory.")

            num_individuals = len(sparse_data)
            for i, sparse_individual in enumerate(sparse_data):
                filename = f"sparse_comparison_{i:03d}.png"
                output_path = os.path.join(OUTPUT_DIR, filename)

                print(f"[{i + 1}/{num_individuals}] Generating visualization -> {output_path}")
                plot_and_save_comparison(original_individual, sparse_individual, output_path)

            print("\n✅ Batch visualization of sparse chromosomes complete!")
        else:
            print("\nThe sparse population file is empty. No visualizations to generate.")